"""
QuantMap — init.py

Interactive onboarding wizard.
Sets up LAB_ROOT, inference paths, and writes the .env configuration.
"""

import os
import sys
from pathlib import Path
from typing import Optional

from rich.prompt import Prompt, Confirm
from src import ui
from src.diagnostics import Status, CheckResult, DiagnosticReport

def run_init():
    """Execute the interactive setup wizard."""
    console = ui.get_console()
    ui.print_banner("QuantMap: Interactive Lab Setup")
    
    console.print("This wizard will help you configure your local benchmarking lab.")
    console.print("Values will be saved to your [bold].env[/bold] file.\n")

    # 1. Discover existing state
    current_lab = os.getenv("QUANTMAP_LAB_ROOT", "")
    current_server = os.getenv("QUANTMAP_SERVER_BIN", "")
    current_model = os.getenv("QUANTMAP_MODEL_PATH", "")

    # 2. LAB_ROOT Setup
    console.print("[bold cyan]Step 1: Lab Root[/bold cyan]")
    console.print("The Lab Root is where all results, logs, and your database will live.")
    
    default_lab = current_lab or str(Path.cwd() / "lab")
    lab_root_str = Prompt.ask("Enter Lab Root path", default=default_lab)
    lab_root = Path(lab_root_str).resolve()

    if not lab_root.exists():
        if Confirm.ask(f"Path [yellow]{lab_root}[/yellow] does not exist. Create it?"):
            try:
                lab_root.mkdir(parents=True, exist_ok=True)
                console.print(f"[green]Created {lab_root}[/green]")
            except Exception as e:
                console.print(f"[bold red]Failed to create Lab Root:[/bold red] {e}")
                sys.exit(1)

    # 3. Paths Validation
    console.print("\n[bold cyan]Step 2: Inference Paths[/bold cyan]")
    
    server_bin_str = Prompt.ask("Enter path to llama-server.exe", default=current_server)
    server_bin = Path(server_bin_str).resolve()
    
    if not server_bin.exists():
        console.print(f"[yellow]{ui.SYM_WARN} Warning: Server binary not found at that path.[/yellow]")
    
    model_path_str = Prompt.ask("Enter default Model path (GGUF)", default=current_model)
    model_path = Path(model_path_str).resolve()
    
    if not model_path.exists():
        console.print(f"[yellow]{ui.SYM_WARN} Warning: Model file not found at that path.[/yellow]")

    # 4. Persistence
    console.print("\n[bold cyan]Step 3: Save Configuration[/bold cyan]")
    
    proposed_env = [
        f"QUANTMAP_LAB_ROOT=\"{lab_root}\"",
        f"QUANTMAP_SERVER_BIN=\"{server_bin}\"",
        f"QUANTMAP_MODEL_PATH=\"{model_path}\"",
        "# Generated by quantmap init"
    ]
    
    console.print("\nProposed [bold].env[/bold] contents:")
    for line in proposed_env:
        console.print(f"  {line}")
        
    if Confirm.ask("\nWrite these settings to .env?"):
        env_path = Path.cwd() / ".env"
        backup_path = Path.cwd() / ".env.bak"
        
        if env_path.exists():
            try:
                env_path.replace(backup_path)
                console.print(f"[dim]Backed up existing .env to .env.bak[/dim]")
            except Exception as e:
                console.print(f"[yellow]Warning: Could not backup .env: {e}[/yellow]")

        try:
            with open(env_path, "w", encoding="utf-8") as f:
                f.write("\n".join(proposed_env) + "\n")
            console.print(f"[bold green]{ui.SYM_OK} Environment configuration saved.[/bold green]")
        except Exception as e:
            console.print(f"[bold red]Failed to write .env:[/bold red] {e}")
            sys.exit(1)

    # 5. Hand-off to Doctor
    console.print("\n[bold cyan]Step 4: Final Wellness Check[/bold cyan]")
    console.print("Running Doctor to verify the new configuration...\n")
    
    from src import doctor
    # Refresh settings in the current process if we want doctor to use them
    os.environ["QUANTMAP_LAB_ROOT"] = str(lab_root)
    os.environ["QUANTMAP_SERVER_BIN"] = str(server_bin)
    os.environ["QUANTMAP_MODEL_PATH"] = str(model_path)
    
    success = doctor.run_doctor(server_bin, model_path, lab_root, fix=True)
    
    if success:
        console.print(f"\n[bold green]Setup Complete![/bold green]")
        console.print(f"  Run [bold]quantmap status[/bold] for a summary.")
        console.print(f"  Run [bold]quantmap run --campaign C01[/bold] to start benchmarking.")
    else:
        console.print(f"\n[bold yellow]Setup complete with warnings.[/bold yellow]")
        console.print(f"  Review the Doctor output above to ensure the lab is clinical-grade.")

if __name__ == "__main__":
    run_init()
